version: '3.5'

services:
  backend:
    container_name: backend
    build: .
    image: spring-boot-dockerized-backend:latest
    networks:
      - database_network
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
      - database_network
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  postgres: