version: '3.5'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    image: spring-boot-dockerized-frontend:latest
    ports:
      - "3000:3000"

  backend:
    container_name: backend
    build: ./backend
    image: spring-boot-dockerized-backend:latest
    networks:
      - database_network
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
      - database_network

networks:
  postgres:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  postgres: